.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "GEM2ARCH" "1" "April 2010" "" ""
.
.SH "NAME"
\fBgem2arch\fR \-\- make gem specifications into PKGBUILDs
.
.SH "SYNOPSIS"
\fBgem2arch\fR \fIGEM\fR [\fI\-o\fR \fIDIRECTORY\fR]
.
.SH "DESCRIPTION"
Create a PKGBUILD from the Ruby gem specification for \fIGEM\fR in directory \fIGEM\fR.
.
.TP
\fB\-o\fR \fIDIRECTORY\fR
Writes PKGBUILD to \fIDIRECTORY\fR instead of \fIGEM\fR.
.
.TP
\fB\-d\fR
Does not create the PKGBUILD but rather simply lists the dependencies given
in the gem specfile. A use of this is to automatically generate the
dependencies of a package by using a loop in shell script.
.
.TP
\fB\-q\fR
Removes any warning or information messages that would be printed. However,
errors will still appear (because they tend to be terminal regardless).
.
.SH "FILES"
If \fB/etc/makepkg.conf\fR exists and \fBPACKAGER\fR is uncommented, \fBgem2arch\fR will
use \fBPACKAGER\fR as the Maintainer for the PKGBUILD.
.
.SH "AUTHORS"
Written by Andrei Thorp and David Campbell.
.
.SH "COPYRIGHT"
gem2arch is Copyright (C) 2010 Andrei Thorp \fIgaroth at the fabulous gmail dot
com\fR
.
.SH "SEE ALSO"
.
.TP
\fBgit repository\fR
\fIhttp://git.mercenariesguild.net/?p=gem2arch\-garoth.git;a=summary\fR

