.\"     Title: pkgfile
.\"    Author: Daenyth Blank <Daenyth+Arch AT gmail DOT com>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: November 27, 2008
.\"    Manual: pkgtools
.\"    Source: pkgfile 7.0
.\"
.TH "PKGFILE" "1" "November 27, 2008" "pkgfile 7\.0" "pkgtools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pkgfile - Find which package owns a file
.SH "SYNOPSIS"
.HP 8
\fBpkgfile\fR [\-\-info] [\-\-list] [\-\-regex] [\-\-search] [\-\-update] [\-\-binaries] [\-\-debug] [\-\-glob] [\-\-limit\-rate] [\-\-remote] [\-\-verbose] {\fIfilename\fR}
.HP 8
\fBpkgfile\fR [\-\-help]
.SH "DESCRIPTION"
.PP

\fBpkgfile\fR
finds which packages own a file\. It derives this information by searching filelists retrieved from active repositories specified in
\fI/etc/pacman\.conf\fR\.
.SH "ACTIONS"
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Show basic help and usage information\.
.RE
.PP
\fB\-\-info\fR, \fB\-i\fR
.RS 4
Provides information about the package owning a file\. Similar to
\fBrpm \-Qf\fR\. The current implementation only allows showing information for local files, but future versions will support searching through uninstalled packages as well\.
.RE
.PP
\fB\-\-list\fR, \fB\-l\fR
.RS 4
List files which belong to a package\. Similar to
\fBpacman \-Ql\fR\.
.RE
.PP
\fB\-\-regex\fR, \fB\-r\fR
.RS 4
Search for a regex instead of a filename\.
.RE
.PP
\fB\-\-search\fR, \fB\-s\fR
.RS 4
Search for what package owns a file\. This is the default action\.
.RE
.PP
\fB\-\-update\fR, \fB\-u\fR
.RS 4
Update to the latest filelist\. This requires write permission for
\fI/usr/share/pkgtools/lists\fR\.
.RE
.SH "OPTIONS"
.PP
\fB\-\-binaries\fR, \fB\-b\fR
.RS 4
When using
\fB\-\-list\fR
or
\fB\-\-search\fR, only show files that pkgfile thinks are binaries; files that are in a
\fIbin/\fR
or
\fIsbin/\fR
directory\.
.RE
.PP
\fB\-\-debug\fR, \fB\-d\fR
.RS 4
Increase debug level\. This can be passed multiple times\.
.RE
.PP
\fB\-\-glob\fR, \fB\-g\fR
.RS 4
Allow using
\fB*\fR
and
\fB?\fR
as basic wildcards in a search\.
.RE
.PP
\fB\-\-limit\-rate\fR, \fB\-L\fR
.RS 4
Limit
\fBwget\fR\'s data transfer rate when using
\fB\-\-update\fR\. This can be permanantly set in
\fIpkgfile\.conf\fR
with the
\fIRATELIMIT\fR
option\.
.RE
.PP
\fB\-\-remote\fR, \fB\-R\fR
.RS 4
Search remotely instead of using
\fBpacman\fR\'s local installation database\. This effects the following options:
.PP
\fB\-\-list\fR
.RS 4

\fBpkgfile\fR
will force the use of
\fBpacman \-Ql\fR
instead of its own routines\.
.RE
.PP
\fB\-\-info\fR
.RS 4

\fBpkgfile\fR
will force the use of
\fBpacman \-Qi\fR
instead of its own routines\.
.RE
.PP
\fB\-\-search\fR
.RS 4

\fBpkgfile\fR
will force the use of
\fBpacman \-Qo\fR
instead of its own routines\.
.RE
.RE
.PP
\fB\-\-verbose\fR, \fB\-v\fR
.RS 4
Enable verbose output\.
.RE
.SH "SHELL HOOKS"
.PP

\fBpkgfile\fR
includes a
command not found
hook for both
\fBbash\fR
and
\fBzsh\fR\. This will automatically run
\fBpkgfile\fR
whenever you run a command which the shell cannot find\. If you want this functionality, set
\fICMD_SEARCH_ENABLED\fR
to
\fB1\fR
in
\fI/etc/pkgtools/pkgfile\.conf\fR
(or per\-user by copying that file to
\fI~/\.pkgtools/pkgfile\.conf\fR), then in your current shell run:
.sp
.RS 4
.nf
$ \fB\. /etc/profile\fR
.fi
.RE
.SH "AUTHOR"
.PP
\fBDaenyth Blank\fR <\&Daenyth+Arch AT gmail DOT com\&>
.sp -1n
.IP "" 4
Author.
