#!/bin/bash

###
# aurball -- Create a tarball ready to upload to the AUR
# This program is a part of pkgtools

# Copyright (C) 2008-2010 Daenyth <Daenyth+Arch _AT_ gmail _DOT_ com>
# 
# Pkgtools is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# Pkgtools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##

PROGNAME="$(basename $0)"
MYVERSION='1.0'

if [ -r /usr/share/pkgtools/functions ]; then
        source /usr/share/pkgtools/functions
else
        printf "Unable to source function file!\n" >&2
        exit 1
fi

BUILDSCRIPT=PKGBUILD

if [ ! -f "$BUILDSCRIPT" ]; then
	die "%s not found!\n" "$BUILDSCRIPT"
fi

pkgname="$(. $BUILDSCRIPT; echo $pkgname)"
aurdir="aur/$pkgname"
rm -rf "$aurdir"
mkdir -p "$aurdir"

sources=($(. $BUILDSCRIPT; echo ${source[@]}; echo $install))
for source in ${sources[@]}; do
	if echo "$source" | grep -qv '://'; then
		cp "$source" "$aurdir"
	fi
done
cp "$BUILDSCRIPT" "$aurdir"

cd aur
msg "Creating new package '%s'...\n" $pkgname
tar -cvzf "$pkgname.tar.gz" "$pkgname"

mv -f "$pkgname.tar.gz" ..
msg "Cleaning up the work directory\n"
cd ..
rm -rf aur
